### ISSUE TITLE
No link to a Google Colab version

### ISSUE THREAD

**Issue by Jakeukalane** [prp-e/mann-e#1]
I think the official Github should contain a link to a Google Colab version, updated and everything. When linking to Voyage 1.0 I had to copy the code and upload a ipynb myself but that is not ideal. I would prefer to avoid that in Mann-e. I prefer a official one, linked in the official repository of the code.

**Comment by prp-e** [comment]
First, I am responsible for both models so this repo can be considered "official". But for your other question, you easily can navigate to "Github" tab in colab welcome page and paste the link to this repo. 
I will update the README.md file though, it's not so hard for me.

**Comment by Jakeukalane** [comment]
Cool. I didn't know that. I'll put those links then :D and thank you for the info it will be useful information from now on.

About Mann-E 3, which base is taking SD 1.5 or SD 2.0 or 2.1? and in Voyage, is Openjourney or really is Midjourney v4?

Thank you!

**Comment by prp-e** [comment]
> Cool. I didn't know that. I'll put those links then :D and thank you for the info it will be useful information from now on.
> 
> About Mann-E 3, which base is taking SD 1.5 or SD 2.0 or 2.1? and in Voyage, is Openjourney or really is Midjourney v4?
> 
> Thank you!

Mann-E uses version 2.1. Voyage uses 2.0. Openjourney is abandoned by me (since the name Openjourney is now adopted by PromptHero's team and Voyage is its replacement). I personally spend more time developing Mann-E as it was the very first generative AI I ever made 😂

And you're welcome my friend.
